#!/bin/bash
#! How much wallclock time will be required?
#SBATCH --time=47:59:00 # Run time
#! Name of the job:
#SBTACH --job-name H100-test
#! Specify the number of GPUs per node (between 1 and n; must be n if nodes>1).
#SBATCH --gres=gpu:2 #*

#! How much wmemory will be required?
#SBATCH --mem 580G #860G #  !TODO cannot be too large, the whole cluster only has 2T --> analysis ecoset, we need to be large
#! How many cpus will be required?
#SBATCH -c 20 #TODO
#! Which partition? klab-gpu klab-l40s gpu
#SBATCH -p gpu
#! How many whole nodes should be allocated?
#SBATCH --nodes 1  # Number of reaquested nodes 
#! Note probably this should not exceed the total number of GPUs in use.
#SBATCH --ntasks=1 #* 2 for 2 gpu
##SBATCH --ntasks-per-node=1          # Number of tasks per node (e.g., GPUs per node)

#! error and output file?
#SBATCH --error=./logs/slurm_logs/h100_multi_error.o%j
#SBATCH --output=./logs/slurm_logs/h100_multi_output.o%j
#! What types of email messages do you wish to receive?
#SBATCH --mail-user=lzejin@uni-osnabrueck.de
##SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --mail-type=REQUEUE
##SBATCH --mail-type=ALL

echo "running in shell: " "$SHELL"
export NCCL_SOCKET_IFNAME=lo

#! new add by zejin
# Set environment variables for NCCL and PyTorch
export OMP_NUM_THREADS=1
export NCCL_DEBUG=INFO


# add by myself
spack unload #unload all the previously loaded packages and load the required packages below
echo $CONDA_PREFIX # to print the path
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/ #Set the path for Nvidia libs
export XLA_FLAGS=--xla_gpu_cuda_data_dir=$CONDA_PREFIX #XLA path specification
echo $LD_LIBRARY_PATH # to print the path

# add by myself 16th Dec
export CUDA_HOME=$CONDA_PREFIX
export PATH=$CUDA_HOME/bin:$PATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH

## Please add any modules you want to load here, as an example we have commented out the modules
## that you may need such as cuda, cudnn, miniconda3, uncomment them if that is your use case 
## term handler the function is executed once the job gets the TERM signal
spack load cuda@11.8.0
spack load cudnn@8.6.0.163-11.8
eval "$(conda shell.bash hook)"
conda activate h100

## -------------------------------------------------------------------------------------------------------------- ##
## Current analysis
## -------------------------------------------------------------------------------------------------------------- ##
# python get_acc_under_sigma_blurring_attack.py
# python get_agreement_with_diff_V1_IT_neural_data.py

## -------------------------------------------------------------------------------------------------------------- ##
## Current training
## -------------------------------------------------------------------------------------------------------------- ##

#! final model
#! adult 63% + 0.45 shape bias, good acc model 63%+ 0.7 shape bias (boom), good trade-off 57-60% acc 0.8 shape bias, good shape bias model 53%-ish acc 0.88+ shape bias
#TODO high acc models looks fine (mpe 4 -8 -3), mpe 2 dn 300 & 100 looks fine (somehow test is 3-5% lower than val), 150 need further train, dn50 might need retrain, mpe1 alpha 0.05-dn50 & alpha 0.1-dn100 on trainning, while alpha 0.1-dn50 need retrain (dn100 wait to see)
#* p1 full_ecoset_evd_mpe2_alpha0.2_dn50, full_ecoset_evd_mpe1_alpha0.1_dn50
# p2 full_ecoset_evd_mpe2_alpha0.1_dn100, full_ecoset_evd_mpe1_alpha0.05_dn50
# p3 full_ecoset_evd_mpe2_alpha0.2_dn300, full_ecoset_evd_mpe1_alpha0.05 or 0.1 _dn300, so for mpe 4/8 alpha 0.4 dn 300
# p4 mpe8 alpha 0.8 dn50 (higher acc higher shape bias) full_ecoset_evd_mpe2_alpha0.05_dn100,
#p1
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=11001 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 2 --contrast_threshold 0.2 --decrease_contrast_threshold_spd 50 --epochs 150 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=11002 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 1 --contrast_threshold 0.1 --decrease_contrast_threshold_spd 50 --epochs 150 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets
#p2
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=11003 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 2 --contrast_threshold 0.1 --decrease_contrast_threshold_spd 100 --epochs 150 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=11004 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 2 --contrast_threshold 0.1 --decrease_contrast_threshold_spd 50 --epochs 150 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets
#p3
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=10184 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 2 --contrast_threshold 0.2 --decrease_contrast_threshold_spd 300 --epochs 150 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=10284 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 2 --contrast_threshold 0.1 --decrease_contrast_threshold_spd 300 --epochs 150 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=10384 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 1 --contrast_threshold 0.1 --decrease_contrast_threshold_spd 300 --epochs 150 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=10484 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 1 --contrast_threshold 0.5 --decrease_contrast_threshold_spd 300 --epochs 150 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=10584 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 4 --contrast_threshold 0.4 --decrease_contrast_threshold_spd 300 --epochs 150 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=10684 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 8 --contrast_threshold 0.4 --decrease_contrast_threshold_spd 300 --epochs 150 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets
#p4
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=10684 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 8 --contrast_threshold 0.8 --decrease_contrast_threshold_spd 50 --epochs 150 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets

#! full ecoset by reducing alpha to 0.05 or dn to 25
#* mpe1
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=10094 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 1 --contrast_threshold 0.05 --decrease_contrast_threshold_spd 50 --epochs 300 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=10084 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 1 --contrast_threshold 0.1 --decrease_contrast_threshold_spd 25 --epochs 300 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets



# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=10060 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy adult --time-order normal --months-per-epoch 2 --contrast_threshold 0.2 --decrease_contrast_threshold_spd 100 --epochs 150 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=10066 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 2 --contrast_threshold 0.1 --decrease_contrast_threshold_spd 100 --epochs 150 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets
# running
# torchrun --nproc_per_node=3 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=10065 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 2 --contrast_threshold 0.2 --decrease_contrast_threshold_spd 100 --epochs 150 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=10073 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 2 --contrast_threshold 0.2 --decrease_contrast_threshold_spd 50 --epochs 150 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=10061 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 3 --contrast_threshold 0.4 --decrease_contrast_threshold_spd 150 --epochs 150 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=10064 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 1 --contrast_threshold 0.1 --decrease_contrast_threshold_spd 100 --epochs 300 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets
#*
# torchrun --nproc_per_node=4 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=10063 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 1 --contrast_threshold 0.1 --decrease_contrast_threshold_spd 50 --epochs 300 --image-size 256 --batch-size 512 --seed 2 /share/klab/datasets
# more
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=10062 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 4 --contrast_threshold 0.4 --decrease_contrast_threshold_spd 150 --epochs 150 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=10072 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 8 --contrast_threshold 0.4 --decrease_contrast_threshold_spd 150 --epochs 150 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets
# extra
# --lr
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=10065 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 2 --contrast_threshold 0.2 --decrease_contrast_threshold_spd 150 --epochs 150 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=10073 scripts/main.py --arch resnet50 --lr 0.00005 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 2 --contrast_threshold 0.2 --decrease_contrast_threshold_spd 50 --epochs 150 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets

# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=10165 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 2 --contrast_threshold 0.2 --decrease_contrast_threshold_spd 300 --epochs 150 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=10174 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 3 --contrast_threshold 0.4 --decrease_contrast_threshold_spd 50 --epochs 150 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets

# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=10111 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name ecoset_square256 --class-weights-json-path '/share/klab/datasets/optimized_datasets/lookup_ecoset_json.json' --development-strategy evd --time-order normal --months-per-epoch 8 --contrast_threshold 0.4 --decrease_contrast_threshold_spd 50 --epochs 150 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets
#* mini ecoset
# torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=10061 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name texture2shape_miniecoset --development-strategy evd --time-order normal --months-per-epoch 1 --contrast_threshold 0.2 --decrease_contrast_threshold_spd 100 --epochs 300 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets

# Setting for development strategy
#* adult 
# resnet50_mpe2_alpha0.2_dn50_texture2shape_miniecoset256_0.0001_dev_evd_b1c1cs1_T_normal_seed_1
# resnet50_mpe2.0_alpha0.2_dn50.0_texture2shape_miniecoset256_0.0001_dev_evd_b1c1cs1_T_normal_seed_1
# torchrun --nproc_per_node=3 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=10055 scripts/main.py --arch resnet50 --lr 0.0001 --label-smoothing 0 --dataset-name texture2shape_miniecoset --development-strategy adult --time-order normal --months-per-epoch 2 --contrast_threshold 0.2 --decrease_contrast_threshold_spd 100 --epochs 300 --image-size 256 --batch-size 512 --seed 1 /share/klab/datasets

#! --lr-scheduler fixed l4 is batch_size/256 * lr set here
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=10050 scripts/main.py --arch resnet50 --lr-scheduler '' --lr 1e-3 --label-smoothing 0 --dataset-name texture2shape_miniecoset --development-strategy evd --time-order normal --months-per-epoch 2 --contrast_threshold 0.2 --decrease_contrast_threshold_spd 100 --epochs 300 --image-size 256 --batch-size 512 '/share/klab/datasets'
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=10051 scripts/main.py --arch resnet50 --lr-scheduler '' --lr 1e-4 --label-smoothing 0 --dataset-name texture2shape_miniecoset --development-strategy evd --time-order normal --months-per-epoch 2 --contrast_threshold 0.2 --decrease_contrast_threshold_spd 100 --epochs 300 --image-size 256 --batch-size 512 '/share/klab/datasets'

# torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=10021 scripts/main.py --arch resnet50  --label-smoothing 0 --dataset-name texture2shape_miniecoset --development-strategy evd --time-order normal --months-per-epoch 2 --contrast_threshold 0.2 --decrease_contrast_threshold_spd 25 --epochs 300 --image-size 256 --batch-size 512 '/share/klab/datasets'
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=10012 scripts/main.py --arch resnet50 --lr-scheduler '' --lr 1e-4 --label-smoothing 0 --dataset-name texture2shape_miniecoset --development-strategy evd --time-order normal --months-per-epoch 2 --contrast_threshold 0.2 --decrease_contrast_threshold_spd 100 --epochs 300 --image-size 256 --batch-size 512 '/share/klab/datasets'
# mini 1 gpu
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=10000 scripts/main.py --arch resnet50 --label-smoothing 0 --dataset-name texture2shape_miniecoset --development-strategy evd --time-order normal --months-per-epoch 2 --contrast_threshold 0.2 --decrease_contrast_threshold_spd 100 --epochs 300 --image-size 256 --batch-size 512 '/share/klab/datasets'
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=10001 scripts/main.py --arch resnet50 --label-smoothing 0 --dataset-name texture2shape_miniecoset --development-strategy evd --time-order normal --months-per-epoch 2 --contrast_threshold 0.2 --decrease_contrast_threshold_spd 25 --epochs 300 --image-size 256 --batch-size 512 '/share/klab/datasets'
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=10002 scripts/main.py --arch resnet50 --label-smoothing 0 --dataset-name texture2shape_miniecoset --development-strategy evd --time-order normal --months-per-epoch 2 --contrast_threshold 0.2 --decrease_contrast_threshold_spd 50 --epochs 300 --image-size 256 --batch-size 512 '/share/klab/datasets'
# torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=10003 scripts/main.py --arch resnet50 --label-smoothing 0 --dataset-name texture2shape_miniecoset --development-strategy adult --time-order normal --months-per-epoch 2 --contrast_threshold 0.2 --decrease_contrast_threshold_spd 100 --epochs 300 --image-size 256 --batch-size 512 '/share/klab/datasets'

#* FEB 20th main | no seed to speed up | looks werid in 2 gu Loss nan two runs sepratel;y ony 256 natch | 512  133s 1024 144 s 
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=10009 scripts/main.py --arch resnet50 --dataset-name texture2shape_miniecoset --development-strategy evd --epochs 150 --months-per-epoch 2 --time-order normal  --contrast_drop_speed_factor 0.2 --decrease_contrast_drop_speed_factor_every_n_month 100 --decrease_speed_of_contrast_drop_speed_factor_every_n_month 2 --image-size 256 --batch-size 512 '/share/klab/datasets'
# audlt
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=10008 scripts/main.py --arch resnet50 --dataset-name texture2shape_miniecoset --development-strategy adult --epochs 150 --image-size 256 --batch-size 512 '/share/klab/datasets'
#* simclr  | somehow it works with 512 batch size while above does not
# torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=10004 scripts/main_simclr.py --arch resnet50 --dataset-name texture2shape_miniecoset --development-strategy evd --epochs 150 --months-per-epoch 2 --time-order normal  --contrast_drop_speed_factor 0.2 --decrease_contrast_drop_speed_factor_every_n_month 100 --decrease_speed_of_contrast_drop_speed_factor_every_n_month 2 --image-size 256 '/share/klab/datasets'

#* works for heavily augmented data
#* audlt
# torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=10012 main_simclr.py --arch resnet50 --epochs 300 --dataset-name texture2shape_miniecoset '/share/klab/datasets'
#* finetune | runnning
# torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=12305 main_lincls.py --arch resnet50 --epochs 300  --pretrained runs/Feb01_01-51-48_hpc3-53/checkpoint_299.pth --saving-name 'adult' --dataset-name texture2shape_miniecoset '/share/klab/datasets'

#* EVD both gpu and kab-gpu
# torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=10003 main_simclr.py --arch resnet50 --epochs 300 --dataset-name texture2shape_miniecoset --development-strategy evd --months-per-epoch 1 --time-order normal  --contrast_drop_speed_factor 0.1 --decrease_contrast_drop_speed_factor_every_n_month 36 --decrease_speed_of_contrast_drop_speed_factor_every_n_month 2 --image-size 256 '/share/klab/datasets'
# torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=10003 main_simclr.py --arch resnet50 --epochs 300 --dataset-name texture2shape_miniecoset --development-strategy evd --months-per-epoch 1 --time-order normal  --contrast_drop_speed_factor 0.05 --decrease_contrast_drop_speed_factor_every_n_month 36 --decrease_speed_of_contrast_drop_speed_factor_every_n_month 2 --image-size 256 '/share/klab/datasets'
#* finetune# Feb04_11-22-14_klab-1
# torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=12305 main_lincls.py --arch resnet50 --epochs 300  --pretrained runs/Feb04_11-22-14_klab-1/checkpoint_299.pth --saving-name 'evd_Feb04_11-22-14_klab-1_v2' --dataset-name texture2shape_miniecoset '/share/klab/datasets'
#* Feb08_06-28-42_hpc3-54
# torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=12305 main_lincls.py --arch resnet50 --epochs 300  --pretrained runs/Feb08_06-28-42_hpc3-54/checkpoint_299.pth --saving-name 'Feb08_06-28-42_hpc3-54' --dataset-name texture2shape_miniecoset '/share/klab/datasets'

#! resume
# torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=10003 main_simclr.py --arch resnet50 --epochs 300 --dataset-name texture2shape_miniecoset --resume runs/Feb06_19-37-46_klab-1/checkpoint_99.pth --development-strategy evd --months-per-epoch 1 --time-order normal  --contrast_drop_speed_factor 0.05 --decrease_contrast_drop_speed_factor_every_n_month 36 --decrease_speed_of_contrast_drop_speed_factor_every_n_month 2 --image-size 256 '/share/klab/datasets'

#TODO data aug not enough?
#* miniecoset + adult
#! more crazy aug
# torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=10012 main_simclr.py --arch resnet50 --epochs 300 --dataset-name texture2shape_miniecoset '/share/klab/datasets'
# torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=10001 main_simclr.py --arch resnet50 --epochs 300 --dataset-name texture2shape_miniecoset '/share/klab/datasets'
#* evd
# torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=10002 main_simclr.py --arch resnet50 --epochs 300 --dataset-name texture2shape_miniecoset --development-strategy evd --months-per-epoch 1 --time-order normal  --contrast_drop_speed_factor 0.05 --decrease_contrast_drop_speed_factor_every_n_month 36 --decrease_speed_of_contrast_drop_speed_factor_every_n_month 2 --image-size 256 '/share/klab/datasets'
#lr --lr 1e-3
# torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=10005 main_simclr.py --arch resnet50 --epochs 300 --dataset-name texture2shape_miniecoset --lr 1e-3 --development-strategy evd --months-per-epoch 1 --time-order normal  --contrast_drop_speed_factor 0.05 --decrease_contrast_drop_speed_factor_every_n_month 36 --decrease_speed_of_contrast_drop_speed_factor_every_n_month 2 --image-size 256 '/share/klab/datasets'
#* --resume and keep training to 600epochs
# torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=10002 main_simclr.py --arch resnet50 --epochs 900 --dataset-name texture2shape_miniecoset --development-strategy evd --resume runs/Jan23_01-41-42_hpc3-54/checkpoint_299.pth --months-per-epoch 1 --time-order normal  --contrast_drop_speed_factor 0.05 --decrease_contrast_drop_speed_factor_every_n_month 36 --decrease_speed_of_contrast_drop_speed_factor_every_n_month 2 --image-size 256 '/share/klab/datasets'
#* fullcoset + evd
# torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=10004 main_simclr.py --arch resnet50 --epochs 300 --dataset-name ecoset_square256 --development-strategy evd --months-per-epoch 1 --time-order normal  --contrast_drop_speed_factor 0.05 --decrease_contrast_drop_speed_factor_every_n_month 36 --decrease_speed_of_contrast_drop_speed_factor_every_n_month 2 --image-size 256 '/share/klab/datasets'

#* finetune | runnning
# torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=12305 main_lincls.py --arch resnet50 --epochs 300  --pretrained runs/Feb01_01-51-48_hpc3-53/checkpoint_299.pth --saving-name 'adult' --dataset-name texture2shape_miniecoset '/share/klab/datasets'

# torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=12345 main_lincls.py --arch resnet50 --epochs 300  --pretrained runs/Jan23_01-41-42_hpc3-54/checkpoint_299.pth --saving-name 'evd_ep299' --dataset-name texture2shape_miniecoset '/share/klab/datasets'
# torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=12346 main_lincls.py --arch resnet50 --lr 1e-3 --epochs 300  --pretrained runs/Jan23_01-41-42_hpc3-54/checkpoint_2999.pth --saving-name 'evd_ep299_lr_1e-4' --dataset-name texture2shape_miniecoset '/share/klab/datasets'
#* 649
# torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=12346 main_lincls.py --arch resnet50 --epochs 300  --pretrained runs/Jan24_20-35-02_hpc3-54/checkpoint_649.pth --saving-name 'evd_ep649_lr_1e-4' --dataset-name texture2shape_miniecoset '/share/klab/datasets'

# torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=12345 main_simclr.py --arch resnet50 --epochs 300 '/share/klab/datasets'

# torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr="localhost" --master_port=12347 main_lincls.py --arch resnet50 --epochs 300  --pretrained checkpoint_299.pth '/share/klab/datasets' 
 
# python main_simsiam.py \
#   -a resnet50 \
#   --dist-url 'tcp://localhost:10001' --multiprocessing-distributed --world-size 1 --rank 0 \
#   --fix-pred-lr \
#   '/share/klab/datasets'


# python main_lincls.py \
#   -a resnet50 \
#   --dist-url 'tcp://localhost:10001' --multiprocessing-distributed --world-size 1 --rank 0 \
#   --pretrained checkpoint_0099.pth.tar \
#   '/share/klab/datasets'