apply_blur: 1
apply_color: 1
apply_contrast: 1
arch: resnet50
batch_size_per_gpu: 512
contrast_threshold: 0.05
data: /share/klab/datasets
dataset_name: texture2shape_miniecoset
decrease_contrast_threshold_spd: 100
development_strategy: adult
dist_url: env://
epochs: 300
evaluate: false
image_size: 256
label_smoothing: 0.0
log_freq: 5
lr: 0.0001
lr_scheduler: ''
momentum: 0.9
months_per_epoch: 1
optimizer: adam
pretrained: ''
resume: ''
save_checkpoint_every_epochs: 5
seed: 0
start_epoch: 0
time_order: normal
warmup_epochs: 0
weight_decay: 1.0e-06
workers: 10
world_size: 1
